### ISSUE TITLE
node.js İbeacon indoor positioning kalman filter

### ISSUE THREAD

**Issue by Joefreedy** [wouterbulten/kalmanjs#15]
edit

**Comment by wouterbulten** [comment]
Hi! The issues on Github are used for bugs and other code related topics. For info on using the library or application questions please see the article: https://www.wouterbulten.nl/blog/tech/lightweight-javascript-library-for-noise-filtering/ Questions can also be placed there as comments. That way other people can also benefit from your questions and all questions are collected in a single place.

For your use case: you will need to call the filter() function of the KalmanFilter object every time you get a new RSSI measurement. Make sure to create one filter object per device you are monitoring.
