### ISSUE TITLE
Using multiple filters causes filtered data to converge

### ISSUE THREAD

**Issue by leonelgalan** [wouterbulten/kalmanjs#2]
When using multiple filters to filter multiple signals, e.g.:

``` js
var filterBlue = new KalmanFilter();
var filterGreen = new KalmanFilter();
var filterGray = new KalmanFilter();
```

It appears as if all the filters are using all data, not just the one passed through them. That's an empirical observation, my JS is not great and I couldn't tell if this was the case through the code. I'm attaching a chart for three signals, the light colors are the raw values and the dark colors are the filtered values. The filter works well individually but it doesn't when instantiated multiple times.

![screen shot 2016-04-29 at 3 00 59 pm](https://cloud.githubusercontent.com/assets/727774/14926673/3f46c62a-0e1b-11e6-8d15-f7c82884d325.png)

**Comment by leonelgalan** [comment]
I'm sorry for the noise in the repo. I tried to simplify the problem and can conclude that the filters are not mixing data and working as expected. I was feeding bad data to the filters in "troubleshooting" code and that caused the issue.

**Comment by wouterbulten** [comment]
@leonelgalan no problem! Glad to hear that you figured it out :)
