### ISSUE TITLE
Measurement error per filter data point?

### ISSUE THREAD

**Issue by alexanderkjeldaas** [wouterbulten/kalmanjs#20]
When filtering data where the interval is variable, wouldn't we need to be able to enter the measurement error per data point, not as a global constant?

**Comment by wouterbulten** [comment]
Thank you for the issue and PR. To make some things clear: Are you modelling a constant system or a system with movement?

**Comment by byoung2** [comment]
I am testing this library for GPS filtering, and I get an accuracy measurement in meters with each measurement (5 to 50 meters typically). So I would convert that to dLat and dLong and this should work?

**Comment by wouterbulten** [comment]
Closing this issue as the original author did not respond, and issues are limited to discussions regarding problems/improvements of the library. Questions can be placed in the blog post https://www.wouterbulten.nl/posts/lightweight-javascript-library-for-noise-filtering/ which also contains many answers to common questions.
