### ISSUE TITLE
Q and R symbol is misrepresented?

### ISSUE THREAD

**Issue by daun-io** [wouterbulten/kalmanjs#22]
I'm kinda new to this kalman filter concept and after few surveys on the web and now I'm really confused about the symbol's representation made in this repository.
I think the measurement noise symbol that is described as Q should be R and process noise symbol that is described as R should be Q.

You can see many of the references are referring Q as a process noise and R as a measurement noise. 

[https://github.com/rlabbe/filterpy/blob/master/filterpy/kalman/kalman_filter.py](https://github.com/rlabbe/filterpy/blob/master/filterpy/kalman/kalman_filter.py)
[http://www.swarthmore.edu/NatSci/echeeve1/Ref/Kalman/MatrixKalman.html](http://www.swarthmore.edu/NatSci/echeeve1/Ref/Kalman/MatrixKalman.html)
[https://www.diva-portal.org/smash/get/diva2:1041201/FULLTEXT01.pdf](https://www.diva-portal.org/smash/get/diva2:1041201/FULLTEXT01.pdf)
[https://arxiv.org/ftp/arxiv/papers/1702/1702.00884.pdf](https://arxiv.org/ftp/arxiv/papers/1702/1702.00884.pdf)
[https://en.wikipedia.org/wiki/Kalman_filter#Underlying_dynamical_system_model](https://en.wikipedia.org/wiki/Kalman_filter#Underlying_dynamical_system_model)

Update*
I saw the comment that you leaved at your blog and I'm still not sure about which definition is closer to the original.
![image](https://user-images.githubusercontent.com/21135812/92844292-a99d2380-f420-11ea-82b6-2fca3164fe93.png)

I'll leave a pull-request if needed, Thanks :)

**Comment by wouterbulten** [comment]
Hi, when I wrote this library I encountered the same issue. As I said in the comment, I followed the same definition as used in Thrun et al. and this is also used in the paper where this library was used (https://ieeexplore.ieee.org/abstract/document/7471364/).

To keep it consistent, I will follow the original definition. In the end, it's a matter of opinion. The workings of the library are the same, regardless of the naming of those variables.
