### ISSUE TITLE
Kalmanjs in real time?

### ISSUE THREAD

**Issue by ruralkan** [wouterbulten/kalmanjs#3]
Hi

Great job, I have a question,  I saw you have a data set to apply Kalman Filter, so, It's possible apply to real time data??

Sorry I newby in javascript

Best regards

**Comment by wouterbulten** [comment]
Yes, it is meant to be used with real time data :)

As in the example (this is ES6):

``` js
import KalmanFilter from 'kalmanjs';

const kf = new KalmanFilter();

console.log(filteredValue = kf.filter( readRealTimeValueFromSomething() ));

... later ...

console.log(filteredValue = kf.filter( readRealTimeValueFromSomething() ));

```

Each time you receive / measure a new data point just apply filter() and you will receive the filtered value. Does that help you?

See also: https://wouterbulten.nl/blog/tech/lightweight-javascript-library-for-noise-filtering/

**Comment by wouterbulten** [comment]
Closed. Please let me know when my comment didn't solve your problem :)
