### ISSUE TITLE
What is the roadmap for release? 

### ISSUE THREAD

**Issue by mikaoelitiana** [wouterbulten/kalmanjs#4]
Hello, 

I have just discovered your plugin and would like to use it in production soon. When do you plan to release this beta version? 

Many thanks

**Comment by wouterbulten** [comment]
Hi!

The code is stable so a proper production release wouldn't be hard to do! Give me a few days :)

**Comment by ghost** [comment]
How to you include the kalman.js into a normal web page?
I include it with a standard script src...
<script src="kalman.js"></script>

gives a 7 Uncaught ReferenceError: KalmanFilter is not defined

when I try to do a
 var kalmanFilter = new KalmanFilter({R: 0.01, Q: 3});

how does one include your library in a standard simple html/javascript web page?

**Comment by wouterbulten** [comment]
@ericalbers please open a new issue if your question is not directly related to the topic of the issue.

That said, you can find a distribution version of the library here https://github.com/wouterbulten/kalmanjs/releases (see the dist folder in the zip file).
