### ISSUE TITLE
Java Version ?

### ISSUE THREAD

**Issue by Anton-Prab** [wouterbulten/kalmanjs#6]
Hai,
 I'm a newbee for this, do you have anything which is Java equivalent for this Javascript. If so it could be more helpful. And also could you add some examples for implementing Kalman filter on realtime data.

Because I actually dont know how to implement it. It will be great if you help.

PS: Sorry for opening it as an issue.

**Comment by wouterbulten** [comment]
Hi @Anton-Prab ! Could you please post your question at my blog? I would like to keep issues for bugs and other problems! See:

https://wouterbulten.nl/blog/tech/lightweight-javascript-library-for-noise-filtering/

If you post there I will take a look at it as soon as possible. There are also a lot of comments by other users there!

**Comment by wouterbulten** [comment]
Regarding your Java request: this library focuses on the Javascript implementation of the 1D Kalman filter, it would however not be very difficult to port one to Java.  This is explained in: https://wouterbulten.nl/blog/tech/kalman-filters-explained-removing-noise-from-rssi-signals/
