### ISSUE TITLE
How to apply on GPS lat long data

### ISSUE THREAD

**Issue by mineofcode** [wouterbulten/kalmanjs#8]
hi,
I have gps noise data. how to smooth that data using kalman filter.
please help me..

**Comment by wouterbulten** [comment]
Hi @masagatech !

Please see https://www.wouterbulten.nl/blog/tech/lightweight-javascript-library-for-noise-filtering/ for more info on how to use the library. There are also a lot of comments there on applying the filter for specific use cases.

I don't have any experience with working on raw GPS data. But, in general you could just apply the the filter on any data stream that comes in; in your case the longitude/latitude date.

**Comment by mineofcode** [comment]
hey @wouterbulten thanks for your valuable reply. 
If you will find anything for my use-case please let me know thanks in advance :)
